<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
	  <PackageReference Include="Solnet.Serum" Version="6.0.13" />
	  <PackageReference Include="System.Text.Json" Version="9.0.0" />
	  <PackageReference Include="xunit" Version="2.5.3" />
	  <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BasicLayer(net)\YC.Common\YC.Common.csproj" />
    <ProjectReference Include="..\..\..\YC.Model\YC.Model.csproj" />
    <ProjectReference Include="..\Solnet-master\src\Solnet.Extensions\Solnet.Extensions.csproj" />
    <ProjectReference Include="..\Solnet-master\src\Solnet.KeyStore\Solnet.KeyStore.csproj" />
    <ProjectReference Include="..\Solnet-master\src\Solnet.Programs\Solnet.Programs.csproj" />
    <ProjectReference Include="..\Solnet-master\src\Solnet.Rpc\Solnet.Rpc.csproj" />
    <ProjectReference Include="..\Solnet-master\src\Solnet.Wallet\Solnet.Wallet.csproj" />
    <ProjectReference Include="..\Solnet.Metaplex-master\Solnet.Metaplex\Solnet.Metaplex.csproj" />
  </ItemGroup>

</Project>
