<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
	  <PackageReference Include="System.Text.Json" Version="9.0.0" />
	  <PackageReference Include="xunit" Version="2.5.3" />
	  <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BasicLayer(net)\YC.Common\YC.Common.csproj" />
    <ProjectReference Include="..\..\..\YC.Model\YC.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Solnet.Extensions">
      <HintPath>..\Solnet-dll\Solnet.Extensions.dll</HintPath>
      <Private>true</Private>
      <CopyLocal>true</CopyLocal>
    </Reference>
    <Reference Include="Solnet.KeyStore">
      <HintPath>..\Solnet-dll\Solnet.KeyStore.dll</HintPath>
      <Private>true</Private>
      <CopyLocal>true</CopyLocal>
    </Reference>
    <Reference Include="Solnet.Metaplex">
      <HintPath>..\Solnet-dll\Solnet.Metaplex.dll</HintPath>
      <Private>true</Private>
      <CopyLocal>true</CopyLocal>
    </Reference>
    <Reference Include="Solnet.Programs">
      <HintPath>..\Solnet-dll\Solnet.Programs.dll</HintPath>
      <Private>true</Private>
      <CopyLocal>true</CopyLocal>
    </Reference>
    <Reference Include="Solnet.Rpc">
      <HintPath>..\Solnet-dll\Solnet.Rpc.dll</HintPath>
      <Private>true</Private>
      <CopyLocal>true</CopyLocal>
    </Reference>
    <Reference Include="Solnet.Serum">
      <HintPath>..\Solnet-dll\Solnet.Serum.dll</HintPath>
      <Private>true</Private>
      <CopyLocal>true</CopyLocal>
    </Reference>
    <Reference Include="Solnet.Wallet">
      <HintPath>..\Solnet-dll\Solnet.Wallet.dll</HintPath>
      <Private>true</Private>
      <CopyLocal>true</CopyLocal>
    </Reference>
  </ItemGroup>

</Project>
